### PR TITLE
Fixed your todo later

### PR DESCRIPTION
**Pull request by 989onan**
Fixed your todo later, it was in the documentation written **exactly** as I needed it, like the stars had aligned. Nice.
https://docs.minecraftforge.net/en/1.18.x/concepts/sides/

### CODE REVIEW

**Comment by 989onan** [comment]
Oh yeah, almost forgot
I got it to run and got a friend of mine in with the non-vr client, with the server running the VFE mod made after pulling this pull request
There are still some notes to make about it when in my VR headset:

Headset: Valve Index and controllers with Valve Index Base stations
Other tracking: None, no extra tracker points
Graphics: Nividia 3080 RTX TI
Processor: AMD Ryzen 7 2700 Eight-Core Processor 3.20 GHz
Ram: 16GB

Running Client and server on same machine, friend's client is connecting over the internet through a port forward like a dedicated server.
Mod was compiled for 40.1.0 forge but was running 40.1.51 forge, which seemed to be incompatable if connecting with the other version, may be the causes of issues below. Need to do more tests

Client, and server were all running 4.1.51 version, except beta tester was running forge-40.1.0. How this worked, I have no clue.



I still need to look into errors above, but greatest issues are below which happen regardless of someone else connected. Client and server running same version:

1. I sometimes clip through the world randomly when using doors and items (flatworld in creative, old terrain with bedrock at zero instead of -64 bout 1.18.2 chunks if that helps)
2. Arrows will shoot from head and are sometimes innaccurate (So like vanilla behavior)
3. Server is not very happy with teleporting, but it somewhat does it.
4. Arrow hitting an entity shot by a player causes a hard crash due to casting the entity to a player entity, which means the methods for grabbing arrow entity target must have been mixed at some point

**Comment by 989onan** [comment]
This should be fixed now. Check "Fixing issues with previous commits" for more info

**Comment by Sascha-T** [comment]
Oops, sorry and thank you for fixing this late night "patch" attempt.
I personally recommend you that instead of working on this hell of a mess I started that you use the official Vivecraft Forge Extensions for 1.18.2 that were appearently released later in the day I tried to port.
You can get them on the official [ViveCraft discord](https://discord.com/invite/2x3QCk8qa9) at this [message](https://canary.discord.com/channels/178567952780623872/543161829325799426/998297065446711316)

Lots of love, I'll merge now.

**Comment by Sascha-T** [comment]
Alternatively it has also now appeared on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/vivecraft-forge-extensions).
Still, regardless, thank you.

**Pull request merged**
